name: Test action

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Wait for status checks'
        id: waitforstatuschecks
        uses: "WyriHaximus/github-action-wait-for-status@0.1.0"
        with:
          ignoreActions: build
          checkInterval: 13
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - uses: actions/checkout@v1
        if: steps.waitforstatuschecks.outputs.status == 'success'

      - name: Run a basic test
        run: |
          echo "Test succeeded"

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Lint with vint
        run: |
          pip install vim-vint
          vint plugin autoload

