name: Test action

on:
  status

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Run a basic test
        run: |
          echo "Test succeeded"

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Lint with vint
        run: |
          pip install vim-vint
          vint plugin autoload

